[package]
name = "telegram-bot"
version = "0.1.0"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]

[dependencies]
"futures" = "0.1.23"
"telegram-bot" = "0.6.1"
"tokio-core" = "0.1.17"
"algorithmia" = "2.1.3"
"serde" = "1.0.70"
"serde_json" = "1.0.24"
"serde_derive" = "1.0.70"