[package]
name = "telegram-bot"
version = "0.1.0"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]

[dependencies]
"futures" = "*"
"telegram-bot" = "*"
"tokio-core" = "*"
"algorithmia" = "2.1.3"
"serde" = "*"
"serde_json" = "*"
"serde_derive" = "*"