[package]
name = "telegram-chatbot"
version = "0.2.0"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
futures = "0.1"
log = "0.4"
telegram-bot-fork = "0.7.8"
tokio = "0.1.15"
algorithmia = "2.1.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
regex = "1.3"
lazy_static = "1.4"
reqwest = "0.9"
