[package]
name = "telegram-chatbot"
version = "0.3.0"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
futures = "0.3"
log = "0.4"
telegram-bot = {git = "https://github.com/telegram-rs/telegram-bot", rev = "16147f6"}
tokio = { version = "0.2", features = ["macros"] }
algorithmia = "2.1.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
regex = "1.3"
lazy_static = "1.4"
reqwest = "0.9"
forecast = "2.0.0"
chrono = "0.4"
