[package]
name = "telegram-bot"
version = "0.1.0"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
telegram-bot-fork = "0.7.7"
tokio = "0.1.15"
algorithmia = "2.1.3"
serde = "1.0.70"
serde_json = "1.0.24"
serde_derive = "1.0.70"
regex = "1.0"
lazy_static = "1.1.0"
reqwest = "0.8"